### PR TITLE
Installation clarification agout apt usage

### PR DESCRIPTION
**Pull request by psytester**
You could give in installation instruction a short hint that ```apt``` is the only supported way in that project.

### CODE REVIEW

**Comment by alexreinert** [comment]
apt is not the only supported way for installing and updating, apt-get works as well. apt is just the better way.

**Comment by psytester** [comment]
It was a proposal only, but it's ok if both ways are working!
But why pointing out the ```apt``` usage is the only stable usage?

_Originally posted by @alexreinert in https://homematic-forum.de/forum/viewtopic.php?f=69&t=51069#p511886_
> für was schreibe ich Befehle hin, wenn du dann doch andere nimmst?

_Originally posted by @alexreinert in https://github.com/alexreinert/piVCCU/issues/158#issuecomment-487618612_
> Bitte nicht mit apt-get, sondern mit apt arbeiten. apt-get hält gerne mal Pakete zurück.

_Originally posted by @alexreinert in https://github.com/alexreinert/piVCCU/issues/160#issuecomment-491504175_
> Please use apt instead of apt-get as written in the documentation.

_Originally posted by @alexreinert in https://github.com/alexreinert/piVCCU/issues/160#issuecomment-491617661_
> apt-get gets all updates, but it has a very defensive way of handling changed dependencies and hold that packages back. apt handles changed dependecies a little bit smother.

**Comment by alexreinert** [comment]
apt-get is stable, too. But in some situations it keeps packages back, when you are using ```apt-get upgrade``` and you have to use ```apt-get dist-upgrade```. ```apt upgrade``` has a better handling of this situations.

**Comment by psytester** [comment]
It's up to you how the installation instructions are described. Between the lines of your support answers it looks instructive.

**Pull request closed without merging**
