### PR TITLE
New README section about update problems

### PR DESCRIPTION
**Pull request by johker01**
After experiencing a problem during the upgrade of piVCCU, I wanted to improve the README and explain how to identify and fix the problem I had (https://github.com/alexreinert/piVCCU/issues/268), so that other people know what to do without needing to open an issue.

### CODE REVIEW

**Comment by alexreinert** [comment]
Thanks for the PR. But the the section is not correct, the correct solution for that issue is just to reboot the system after the update, like you should do it after every kernel update. There are already some startup task, which will build the kernel modules in case you boot the system with a new kernel.

Second, a forced rebuild can be done without reinstall of the package using ```dpkg-reconfigure pivccu-modules-dkms```

**Comment by johker01** [comment]
Would your suggestion be to leave the README as it is? My intention was to help people in a similar situation than I've been. I was hesitant to just reboot my system after getting an error building kernel modules, but you're saying that I could/should have done that and that the system would have fixed itself (I'm referring to those startup tasks you mentioned).
So basically, my problem was that I was in "headless chicken" mode after seeing that error message and reinstalling the kernel + headers and removing pivccu did more harm than good in this situation, right?

**Comment by alexreinert** [comment]
I do not want to have invalid information in the Readme.
As an idea, I will add a hint directly to the module package. I think, this will prevent the chicken better than a hint in the Readme, which will not be read in most cases.

**Comment by johker01** [comment]
My intention was not to put misinformation in the README, my intention was to save you time and help people quickly find a solution to the problem, which I stated in the description of the PR. The error message generated by `pivccu-modules-dkms` didn't help me debug the problem or find help on the internet. If there were a way to improve that message and show a solution, that would be the best solution as it would be local to the problem, I agree. You are probably right that most people won't read the README, but by putting a troubleshooting section somewhere else in your github repo, it is possible to find the solution by googling for keywords and I hope that people do at least that before opening issues or reporting problems in homematic-forum.de.

**Pull request closed without merging**
